/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    VisibilityCredits: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "treasury",
              type: "address",
            },
            {
              internalType: "address",
              name: "creatorLinker",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AccessControlBadConfirmation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          name: "AccessControlEnforcedDefaultAdminDelay",
          type: "error",
        },
        {
          inputs: [],
          name: "AccessControlEnforcedDefaultAdminRules",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "defaultAdmin",
              type: "address",
            },
          ],
          name: "AccessControlInvalidDefaultAdmin",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "neededRole",
              type: "bytes32",
            },
          ],
          name: "AccessControlUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "AddressInsufficientBalance",
          type: "error",
        },
        {
          inputs: [],
          name: "FailedInnerCall",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAmount",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidCreator",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidFeeParams",
          type: "error",
        },
        {
          inputs: [],
          name: "NotEnoughCreditsOwned",
          type: "error",
        },
        {
          inputs: [],
          name: "NotEnoughEthSent",
          type: "error",
        },
        {
          inputs: [],
          name: "ReentrancyGuardReentrantCall",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "bits",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "SafeCastOverflowedUintDowncast",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "CreatorFeeClaimed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          name: "CreatorVisibilitySet",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              components: [
                {
                  internalType: "address",
                  name: "from",
                  type: "address",
                },
                {
                  internalType: "string",
                  name: "visibilityId",
                  type: "string",
                },
                {
                  internalType: "uint256",
                  name: "amount",
                  type: "uint256",
                },
                {
                  internalType: "bool",
                  name: "isBuy",
                  type: "bool",
                },
                {
                  internalType: "uint256",
                  name: "tradeCost",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "creatorFee",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "protocolFee",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "referrerFee",
                  type: "uint256",
                },
                {
                  internalType: "address",
                  name: "referrer",
                  type: "address",
                },
                {
                  internalType: "uint256",
                  name: "newTotalSupply",
                  type: "uint256",
                },
                {
                  internalType: "uint256",
                  name: "newCurrentPrice",
                  type: "uint256",
                },
              ],
              indexed: false,
              internalType: "struct IVisibilityCredits.CreditsTradeEvent",
              name: "tradeEvent",
              type: "tuple",
            },
          ],
          name: "CreditsTrade",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "CreditsTransfer",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [],
          name: "DefaultAdminDelayChangeCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
            {
              indexed: false,
              internalType: "uint48",
              name: "effectSchedule",
              type: "uint48",
            },
          ],
          name: "DefaultAdminDelayChangeScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [],
          name: "DefaultAdminTransferCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint48",
              name: "acceptSchedule",
              type: "uint48",
            },
          ],
          name: "DefaultAdminTransferScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "previousAdminRole",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "newAdminRole",
              type: "bytes32",
            },
          ],
          name: "RoleAdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleRevoked",
          type: "event",
        },
        {
          inputs: [],
          name: "A",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "B",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "BASE_PRICE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "CREATORS_CHECKER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "CREATOR_FEE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "CREDITS_TRANSFER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DEFAULT_ADMIN_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "FEE_DENOMINATOR",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "MAX_TOTAL_SUPPLY",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "PROTOCOL_FEE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "REFERRER_FEE",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "acceptDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "beginDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referrer",
              type: "address",
            },
          ],
          name: "buyCostWithFees",
          outputs: [
            {
              internalType: "uint256",
              name: "totalCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tradeCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "creatorFee",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "protocolFee",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "referrerFee",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referrer",
              type: "address",
            },
          ],
          name: "buyCredits",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "cancelDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
          ],
          name: "changeDefaultAdminDelay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
          ],
          name: "claimCreatorFee",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdmin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdminDelay",
          outputs: [
            {
              internalType: "uint48",
              name: "",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdminDelayIncreaseWait",
          outputs: [
            {
              internalType: "uint48",
              name: "",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
          ],
          name: "getRoleAdmin",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
          ],
          name: "getVisibility",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalSupply",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "claimableFeeBalance",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "getVisibilityCreditBalance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
          ],
          name: "getVisibilityCurrentPrice",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
          ],
          name: "getVisibilityKey",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "grantee",
              type: "address",
            },
          ],
          name: "grantCreatorTransferRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "grantRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "hasRole",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingDefaultAdmin",
          outputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingDefaultAdminDelay",
          outputs: [
            {
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "protocolTreasury",
          outputs: [
            {
              internalType: "address payable",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "renounceRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "revokeRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "rollbackDefaultAdminDelay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referrer",
              type: "address",
            },
          ],
          name: "sellCostWithFees",
          outputs: [
            {
              internalType: "uint256",
              name: "reimbursement",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "tradeCost",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "creatorFee",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "protocolFee",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "referrerFee",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "referrer",
              type: "address",
            },
          ],
          name: "sellCredits",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
          ],
          name: "setCreatorVisibility",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "transferCredits",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "treasury",
              type: "address",
            },
          ],
          name: "updateTreasury",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          name: "visibilityCredits",
          outputs: [
            {
              internalType: "address",
              name: "creator",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "totalSupply",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "claimableFeeBalance",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        buyCostWithFees: "contracts/interfaces/IVisibilityCredits.sol",
        buyCredits: "contracts/interfaces/IVisibilityCredits.sol",
        claimCreatorFee: "contracts/interfaces/IVisibilityCredits.sol",
        getVisibility: "contracts/interfaces/IVisibilityCredits.sol",
        getVisibilityCreditBalance:
          "contracts/interfaces/IVisibilityCredits.sol",
        getVisibilityCurrentPrice:
          "contracts/interfaces/IVisibilityCredits.sol",
        getVisibilityKey: "contracts/interfaces/IVisibilityCredits.sol",
        sellCostWithFees: "contracts/interfaces/IVisibilityCredits.sol",
        sellCredits: "contracts/interfaces/IVisibilityCredits.sol",
        setCreatorVisibility: "contracts/interfaces/IVisibilityCredits.sol",
        transferCredits: "contracts/interfaces/IVisibilityCredits.sol",
        updateTreasury: "contracts/interfaces/IVisibilityCredits.sol",
        DEFAULT_ADMIN_ROLE:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        acceptDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        beginDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        cancelDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        changeDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdminDelayIncreaseWait:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        getRoleAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        grantRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        hasRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        owner:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        pendingDefaultAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        pendingDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        renounceRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        revokeRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        rollbackDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        supportsInterface:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
      },
    },
    VisibilityServices: {
      address: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_visibilityCredits",
              type: "address",
            },
            {
              internalType: "address",
              name: "disputeResolver",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          inputs: [],
          name: "AccessControlBadConfirmation",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          name: "AccessControlEnforcedDefaultAdminDelay",
          type: "error",
        },
        {
          inputs: [],
          name: "AccessControlEnforcedDefaultAdminRules",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "defaultAdmin",
              type: "address",
            },
          ],
          name: "AccessControlInvalidDefaultAdmin",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              internalType: "bytes32",
              name: "neededRole",
              type: "bytes32",
            },
          ],
          name: "AccessControlUnauthorizedAccount",
          type: "error",
        },
        {
          inputs: [],
          name: "DisabledService",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidAddress",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidCreator",
          type: "error",
        },
        {
          inputs: [],
          name: "InvalidExecutionState",
          type: "error",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "bits",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "SafeCastOverflowedUintDowncast",
          type: "error",
        },
        {
          inputs: [],
          name: "UnauthorizedExecutionAction",
          type: "error",
        },
        {
          anonymous: false,
          inputs: [],
          name: "DefaultAdminDelayChangeCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
            {
              indexed: false,
              internalType: "uint48",
              name: "effectSchedule",
              type: "uint48",
            },
          ],
          name: "DefaultAdminDelayChangeScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [],
          name: "DefaultAdminTransferCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint48",
              name: "acceptSchedule",
              type: "uint48",
            },
          ],
          name: "DefaultAdminTransferScheduled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "previousAdminRole",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "bytes32",
              name: "newAdminRole",
              type: "bytes32",
            },
          ],
          name: "RoleAdminChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleGranted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "address",
              name: "account",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "sender",
              type: "address",
            },
          ],
          name: "RoleRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "serviceType",
              type: "string",
            },
            {
              indexed: false,
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "creditsCostAmount",
              type: "uint256",
            },
          ],
          name: "ServiceCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "responseData",
              type: "string",
            },
          ],
          name: "ServiceExecutionAccepted",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "cancelData",
              type: "string",
            },
          ],
          name: "ServiceExecutionCanceled",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "string",
              name: "disputeData",
              type: "string",
            },
          ],
          name: "ServiceExecutionDisputed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "requester",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "requestData",
              type: "string",
            },
          ],
          name: "ServiceExecutionRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "refund",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "string",
              name: "resolveData",
              type: "string",
            },
          ],
          name: "ServiceExecutionResolved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
          ],
          name: "ServiceExecutionValidated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "nonce",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "ServiceUpdated",
          type: "event",
        },
        {
          inputs: [],
          name: "AUTO_VALIDATION_DELAY",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DEFAULT_ADMIN_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "DISPUTE_RESOLVER_ROLE",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "acceptDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "responseData",
              type: "string",
            },
          ],
          name: "acceptServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
          ],
          name: "beginDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "cancelDefaultAdminTransfer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "cancelData",
              type: "string",
            },
          ],
          name: "cancelServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
          ],
          name: "changeDefaultAdminDelay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "serviceType",
              type: "string",
            },
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "creditsCostAmount",
              type: "uint256",
            },
          ],
          name: "createService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdmin",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdminDelay",
          outputs: [
            {
              internalType: "uint48",
              name: "",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "defaultAdminDelayIncreaseWait",
          outputs: [
            {
              internalType: "uint48",
              name: "",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "disputeData",
              type: "string",
            },
          ],
          name: "disputeServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
          ],
          name: "getRoleAdmin",
          outputs: [
            {
              internalType: "bytes32",
              name: "",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
          ],
          name: "getServiceExecution",
          outputs: [
            {
              internalType: "enum VisibilityServices.ExecutionState",
              name: "state",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "requester",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "lastUpdateTimestamp",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "grantRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "hasRole",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingDefaultAdmin",
          outputs: [
            {
              internalType: "address",
              name: "newAdmin",
              type: "address",
            },
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "pendingDefaultAdminDelay",
          outputs: [
            {
              internalType: "uint48",
              name: "newDelay",
              type: "uint48",
            },
            {
              internalType: "uint48",
              name: "schedule",
              type: "uint48",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "renounceRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "string",
              name: "requestData",
              type: "string",
            },
          ],
          name: "requestServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "refund",
              type: "bool",
            },
            {
              internalType: "string",
              name: "resolveData",
              type: "string",
            },
          ],
          name: "resolveServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "role",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "revokeRole",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "rollbackDefaultAdminDelay",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "services",
          outputs: [
            {
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
            {
              internalType: "string",
              name: "serviceType",
              type: "string",
            },
            {
              internalType: "string",
              name: "visibilityId",
              type: "string",
            },
            {
              internalType: "uint256",
              name: "creditsCostAmount",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionsNonce",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "servicesNonce",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes4",
              name: "interfaceId",
              type: "bytes4",
            },
          ],
          name: "supportsInterface",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "enabled",
              type: "bool",
            },
          ],
          name: "updateService",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "serviceNonce",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "executionNonce",
              type: "uint256",
            },
          ],
          name: "validateServiceExecution",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "visibilityCredits",
          outputs: [
            {
              internalType: "contract IVisibilityCredits",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
      ],
      inheritedFunctions: {
        DEFAULT_ADMIN_ROLE:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        acceptDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        beginDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        cancelDefaultAdminTransfer:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        changeDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        defaultAdminDelayIncreaseWait:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        getRoleAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        grantRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        hasRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        owner:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        pendingDefaultAdmin:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        pendingDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        renounceRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        revokeRole:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        rollbackDefaultAdminDelay:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
        supportsInterface:
          "@openzeppelin/contracts/access/extensions/AccessControlDefaultAdminRules.sol",
      },
    },
    YourContract: {
      address: "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "_owner",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "greetingSetter",
              type: "address",
            },
            {
              indexed: false,
              internalType: "string",
              name: "newGreeting",
              type: "string",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "premium",
              type: "bool",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "GreetingChange",
          type: "event",
        },
        {
          inputs: [],
          name: "greeting",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "premium",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_newGreeting",
              type: "string",
            },
          ],
          name: "setGreeting",
          outputs: [],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [],
          name: "totalCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          name: "userGreetingCounter",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "withdraw",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          stateMutability: "payable",
          type: "receive",
        },
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
